spring:
  sql:
    init:
      mode: always
  mvc:
    static-path-pattern: /resources/**
  messages:
    basename: classpath:/messages
    encoding: utf-8
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB
  jpa:
    hibernate:
      ddl-auto: update # 필요에 맞게 설정 (validate, none 등)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8.x 이상일 경우
        show-sql: true
        connection:
          provider_disables_autocommit: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jangbiplannet
    username: janbi
    password: newpassword
    hikari:   # HikariCP 설정 추가
      maximum-pool-size: 10  # HikariCP 설정에 맞춰 수정
